name: Run Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # 更新到最新版本

    - name: Set up Maven
      run: |
        sudo apt update
        sudo apt install -y maven

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Run tests normally
      run: mvn test

    - name: Run tests with NonDex
      run: mvn edu.illinois:nondex-maven-plugin:1.1.2:nondex
